# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oXtwahxW4pc1uvpOipFgqFeIoSj4qNmR
"""

# initialization:
!pip install pygad
!wget https://github.com/ZilongBai/KDD2020BMGUFS/raw/master/dataset.zip
!unzip dataset.zip
!mkdir results