# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oXtwahxW4pc1uvpOipFgqFeIoSj4qNmR
"""

# Loading Dataset

import numpy as np
import torch

datastr = 'dataset/'
resultstr = 'results/'

print('Loading raw graph...')
Original_X = np.genfromtxt((datastr+'BlogCatalog_Network.csv'),delimiter=',')

print('Loading nodal attributes...')
Original_Y = np.genfromtxt((datastr+'BlogCatalog_Attributes.csv'),delimiter=',')

kmin = 6; kmax = 6;
repmax = 10;
gammas = [4] # Grid-search
betas = [0]
MAXITER = 200 # 200 iterations. 
step_size = 1e-2
delta = 1e-6

repselected = 3 # Lowest RRE.

kstr = str(kmin);

# At each k, we first find which block model achieves the lowest reconstruction loss
rep = repselected
repstr = str(rep) # Already aligned rep to start at 1. No need to add 1 to translate to matlab indexing.

print('Loading block allocation ...')
Original_F = np.genfromtxt((datastr+'blogcatalog_nmtf_'+kstr+'_'+repstr+'_F.csv'),delimiter=',');

print('Loading mixing/image matrix ...')
Original_Ms = np.genfromtxt((datastr+'blogcatalog_nmtf_'+kstr+'_'+repstr+'_M.csv'),delimiter=',');