# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oXtwahxW4pc1uvpOipFgqFeIoSj4qNmR
"""

X = np.copy(Original_X)
Y = np.copy(Original_Y)
Ms = np.copy(Original_Ms);
F = np.copy(Original_F);
E = X + X.transpose()
E[np.where(X>0)] = 1
ga_instance = solver_delta_enhanced_sparse(X,Y,F,Ms,delta)

r, solution_fitness, solution_idx = ga_instance.best_solution()
np.savetxt(resultstr+'ours_blogcatalog_r.csv',r,delimiter=',')
ga_instance.plot_fitness()