# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oXtwahxW4pc1uvpOipFgqFeIoSj4qNmR
"""

# plot bars for accuracy
#

# MImax = 100*Accmax
fig = plt.figure(figsize = (10, 5))
plt.show()
x = np.arange(5)
width = 0.1
# plot data in grouped manner of bar type
plt.bar(x-0.15, AccV, width, color='green')
# plt.bar(x, Accmax, width, color='yellow')
# plt.bar(x-0.3, AC, width, color='red')
plt.xticks(x,['16','64','128','200','600'])
plt.xlabel("Number of selected features",fontsize=16)
plt.ylabel("ACC(%)",fontsize=16)
plt.title("Accuracy on BlogCatalog")
plt.legend(["GA based accuracy"],loc='upper left')
plt.show()